#!/usr/bin/python3

import psutil
import click
from commentedconfigparser import CommentedConfigParser

@click.command()
@click.option('--wfb_cfg', default='wfb_server.cfg', help='target cfg file, default wfb_server.cfg')
@click.option('--prfx', default='wlx', help='wlan interface prefix wlx, wl, wlan, default is wlx')
@click.option('--channel', default='149', help='wifi channel, default is 149')
@click.option('--wlans_nmbr', default=1, help='number of wlans will be added, default is 1')
@click.option('--wlan_section', default='wlan', help='wlan section of wfb_cfg file, default is wlan')

def main(wfb_cfg, prfx, channel, wlans_nmbr, wlan_section):
    
    def get_wlans_list(prfx):
        wlans = []
        if_list = psutil.net_if_addrs().keys()
        for if_name in if_list:
            if if_name[:len(prfx)] == prfx:
                wlans.append(if_name)
        
        return wlans
    
#--------------------------------------------
    config = CommentedConfigParser()
    config.read(wfb_cfg)

    wlans_list = get_wlans_list(prfx)
    wlans = ''

    for wlan_idx in range(wlans_nmbr):
        if wlan_idx > 0:
            wlans += ' '
        wlans += wlans_list[wlan_idx]

    config[wlan_section]['wlan'] = wlans
    #config[wlan_section]['channel'] = channel

    with open(wfb_cfg,'w') as configfile:
        config.write(configfile)

if __name__ == '__main__':
    main()