#!/usr/bin/python3

import socket
import serial
import time

UDP_IP_PROXY = "192.168.144.75"
UDP_PORT_PROXY = 14775

UDP_IP_MvPr = "192.168.144.50"
UDP_PORT_MvPr = 14550

# UART CONF
UART_PORT_1 = '/dev/ttyS0' 
UART_BAUDRATE_1 = 115200

UART_PORT_2 = '/dev/ttyS4'
UART_BAUDRATE_2 = 115200

# --- stat info
#time_int = 1

print ("Proxy initialization...\n")
# main loop for try...except
while True:
    try:
        ser_1 = serial.Serial(UART_PORT_1, UART_BAUDRATE_1)
        ser_2 = serial.Serial(UART_PORT_2, UART_BAUDRATE_2)
        print ("Serial ports... ok")
        sock_proxy = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock_proxy.bind((UDP_IP_PROXY, UDP_PORT_PROXY))
        print ("Proxy socket... ok\n")
        print ("Proxy loop starting...")
        # for stat info
        #pkt_alfa = 0
        #pkt_gs = 0
        #time_ls = time.time()
        
        while True:
            data, addr = sock_proxy.recvfrom(2048)

            if addr[0] == UDP_IP_MvPr:
                ser_1.write(data)
                ser_2.write(data)
        # --- stat info    
        #        pkt_gs +=1
            else:
                sock_proxy.sendto(data, (UDP_IP_MvPr, UDP_PORT_MvPr))
        # --- stat info    
        #        pkt_alfa +=1
            
        # --- stat info
        #    if (time.time() - time_ls) >= time_int:
        #        print(f"alfa: {pkt_alfa} pkt/s")
        #        print(f"gs: {pkt_gs} pkt/s")
        #        pkt_alfa = 0
        #        pkt_gs = 0
        #        time_ls = time.time()
                
    except Exception as e:
        print(f"error: {e}")
        time.sleep(1)
        
        
