#!/usr/bin/python3
import socket
import click

@click.command()
@click.option('--mpkts', default=2048, help='udp max pkt size def: 2048')
@click.option('--ip_rx', default='0.0.0.0', help='ip of sorce stream def: 127.0.0.1')
@click.option('--port_rx', default=5700, help='port of source stream def: 5700')
@click.option('--ip_tx', default='127.0.0.1', help='ip of destination host def: 127.0.0.1')
@click.option('--port_tx', default=5800, help='first port of destination hosts def: 5680')

def main(mpkts,ip_rx,port_rx,ip_tx,port_tx):
    
    tcp_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    tcp_socket.bind((ip_rx, port_rx))
    tcp_socket.listen(1)
    conn, addr = tcp_socket.accept()
    
    udp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    
    while True:
        data = conn.recv(1024)
        if not data:
            break
        udp_socket.sendto(data, (ip_tx, port_tx))

    return


if __name__ == '__main__':
    main()

