#!/usr/bin/python3

import serial
import socket
import click

#UART_PORT_1 = '/dev/ttyS0' 
#UART_BAUDRATE_1 = 115200 

#UART_PORT_2 = '/dev/ttyS4'
#UART_BAUDRATE_2 = 115200  

#UDP_SERVER_IP = '127.0.0.1'
#UDP_SERVER_PORT = 14775

STX_v2_0 = b'\xfd'
STX_v1_0 = b'\xfe'
STX_v0_9 = b'\x55'

@click.command()
@click.option('--uart', default='/dev/ttyS0', help='uart port name def: /dev/ttyS0')
@click.option('--brate', default=115200, help='uart port baudrate def: 115200')
@click.option('--udps_ip', default='127.0.0.1', help='udp server ip def: 127.0.0.1')
@click.option('--udps_port', default=14775, help='ip of source host')

def main(uart,brate,udps_ip,udps_port):

    UART_PORT = uart
    UART_BAUDRATE = brate
    UDP_SERVER_IP = udps_ip
    UDP_SERVER_PORT = udps_port

    ser = serial.Serial(UART_PORT, UART_BAUDRATE)
    udp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    udp_address = (UDP_SERVER_IP, UDP_SERVER_PORT)
    print("uart_to_udp have started...")
    print (f"{UART_PORT}:{UART_BAUDRATE}")
    print (f"{udp_address}")
    while True:

        start_of_frame = ser.read(1)
        if start_of_frame == STX_v2_0:
            header = ser.read(9)
            payload_length = header[0]
            mavlink_packet = start_of_frame + header + ser.read(payload_length) + ser.read(2)
            if header[1] == 1:
                mavlink_packet += ser.read(13)
            udp_socket.sendto(mavlink_packet, udp_address)
        elif start_of_frame == STX_v1_0:
            header = ser.read(5)
            payload_length = header[0]
            mavlink_packet = start_of_frame + header + ser.read(payload_length) + ser.read(2)

if __name__ == '__main__':
    main()