#!/usr/bin/python3
import socket
import struct
import click
import zfec
import signal
import atexit
import sys


def fec_encode(d_k,d_m,bloks: list) -> list:
    encoder = zfec.Encoder(d_k, d_m)
    try:
        encoded_blocks = encoder.encode(bloks)
    except Exception as e:
        encoded_blocks = []            
    return encoded_blocks    

def blocks_encoder(blocks: list) -> list:
    encoded_blocks = []
    max_block_size = 0
    for block in blocks:
        block_size = len(block)
        if block_size > max_block_size:
            max_block_size = block_size
    for block in blocks:
        block_size = len(block)
        if block_size < max_block_size:
            ext_block = b"\xFF"*(max_block_size-block_size)
            encoded_block = struct.pack("!I"+str(block_size)+"s"+ str(len(ext_block))+"s", block_size, block, ext_block)
        else:
            encoded_block = struct.pack("!I"+str(block_size)+"s", block_size, block)
        encoded_blocks.append(encoded_block)
    return encoded_blocks

def ring_blocks_encoder(rb_id,e_k,e_m, blocks: list) -> list:
    encoded_blocks = []
    block_number = 0
    for block in blocks:
        block_size = len(block)
        encoded_block = struct.pack("!IIII"+str(block_size)+"s",rb_id, block_number, e_k, e_m, block)
        encoded_blocks.append(encoded_block)
        block_number+=1
    return encoded_blocks

@click.command()
@click.option('--mpkts', default=2048, help='udp max pkt size def: 2048')
@click.option('--ip_rx', default='0.0.0.0', help='ip of sorce stream def: 0.0.0.0')
@click.option('--port_rx', default=7600, help='port of source stream def: 7600')
@click.option('--ip_tx', default='127.0.0.1', help='ip of destination host def: 127.0.0.1')
@click.option('--port_tx', default=7700, help='port of destination hosts def: 7700')
@click.option('--k', default=3, help='fec k param (min fec blocks number to be recoverd) def: 3')
@click.option('--m', default=6, help='fec m param (fec bloks number of fec ring) def: 6')

def main(mpkts,ip_rx,port_rx,ip_tx,port_tx,k,m):

    sock_tx = None
    sock_rx = None

    def cleanup():
        for s in (sock_rx, sock_tx):
            try:
                if s is not None:
                    s.close()
            except Exception as e:
                print(e)

    def signal_handler(sig, frame):
        cleanup()
        sys.exit(0)

    atexit.register(cleanup)
    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)

    sock_tx = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    sock_rx = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock_rx.bind((ip_rx, port_rx))

    print("udp_fec_tx started...")
    print(f"rx: {ip_rx} : {port_rx}")
    print(f"tx: {ip_tx} : {port_tx}")
    print(f"k: {k}")
    print(f"m: {m}")
    
    fec_ring_id = 0

    try:
        while True:
            fec_ring_id +=1 
            fec_ring_data = []

            while len(fec_ring_data) < k:
                try:
                    data, addr = sock_rx.recvfrom(mpkts)
                except OSError:
                    fec_ring_data = []
                    break
                fec_ring_data.append(data)

            if len(fec_ring_data) < k:
                break

            encoded_blocks = blocks_encoder(fec_ring_data)
            encoded_fragments = fec_encode(k,m,encoded_blocks)
            ring_tx_blocks = ring_blocks_encoder(fec_ring_id,k,m,encoded_fragments)

            for tx_block in ring_tx_blocks:
                sock_tx.sendto(tx_block,(ip_tx, port_tx))
    finally:
        cleanup()


if __name__ == '__main__':
    main()
