#!/usr/bin/python3
import socket
import click

@click.command()
@click.option('--mpkts', default=4096, help='udp max pkt size def: 2048')
@click.option('--ip_rx', default='0.0.0.0', help='ip of sorce stream def: 127.0.0.1')
@click.option('--port_rx', default=5700, help='port of source stream def: 5700')
@click.option('--ip_tx', default='127.0.0.1', help='ip of destination host def: 127.0.0.1')
@click.option('--port_tx', default=5800, help='first port of destination hosts def: 5680')

def main(mpkts,ip_rx,port_rx,ip_tx,port_tx):
    
    print("UDP to TCP fwd")
    print(f"ip_rx: {ip_rx} port_rx: {port_rx}")
    print(f"ip_tx: {ip_tx} port_tx: {port_tx}")
    udp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    udp_socket.bind((ip_rx, port_rx))
        
    tcp_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    print(f"\ntrying to connect {ip_tx}:{port_tx}...\n")

    ext = False
    while not ext:
        try: 
            tcp_socket.connect((ip_tx, port_tx))
            ext = True
        except:
            pass
    laddr = tcp_socket.getsockname()
    raddr = tcp_socket.getpeername()   
    print(f"connection established successful...\nladdr:{laddr} raddr:{raddr}")    
    print(tcp_socket.getsockopt(socket.SOL_SOCKET,socket.SO_RCVBUF))
    print(tcp_socket.getsockopt(socket.SOL_SOCKET,socket.SO_SNDBUF))
        
    while True:
        data, addr = udp_socket.recvfrom(mpkts)
        tcp_socket.sendall(data)
    
    return


if __name__ == '__main__':
    main()

